from enum import StrEnum


class PortfolioEvent(StrEnum):
    POSITION_OPENED = "POSITION_OPENED"
    POSITION_CLOSED = "POSITION_CLOSED"

    STOP_TRIGGERED = "STOP_TRIGGERED"
    TARGET_TRIGGERED = "TARGET_TRIGGERED"

    WAITING_FOR_LIQUIDITY = "WAITING_FOR_LIQUIDITY"

    ORDER_FILLED = "ORDER_FILLED"
