"""Deterministic recommendation intelligence primitives.

M14 converts market intelligence, strategy evidence, empirical probability,
and portfolio context into explainable, auditable recommendation reports.
"""

from __future__ import annotations

from alpha.recommendation_intelligence.engines import (
    CandlePatternEngine,
    EvidenceScoringEngine,
    ExpectedValueEngine,
    OpportunityCostEngine,
    PortfolioAwarenessEngine,
    PriceVolumeSignalEngine,
    RecommendationEngine,
    RecommendationScoringEngine,
)
from alpha.recommendation_intelligence.models import (
    AllocationAdjustment,
    CandidateComparison,
    CandlePatternAssessment,
    EvidenceAssessment,
    EvidenceDirection,
    EvidenceSignal,
    ExpectedValueAssessment,
    HistoricalExpectancy,
    OpportunityCostAssessment,
    PortfolioContext,
    PriceEvidence,
    PriceVolumeAssessment,
    RecommendationAction,
    RecommendationCandidate,
    RecommendationDecision,
    RecommendationEvidence,
    RecommendationReport,
    RecommendationRisk,
    RecommendationScore,
    RecommendationScoreBreakdown,
    RecommendationTradePlan,
    SetupQualityAssessment,
    VolumeEvidence,
)

__all__ = [
    "AllocationAdjustment",
    "CandlePatternAssessment",
    "CandlePatternEngine",
    "CandidateComparison",
    "EvidenceAssessment",
    "EvidenceDirection",
    "EvidenceScoringEngine",
    "EvidenceSignal",
    "ExpectedValueAssessment",
    "ExpectedValueEngine",
    "HistoricalExpectancy",
    "OpportunityCostAssessment",
    "OpportunityCostEngine",
    "PortfolioAwarenessEngine",
    "PortfolioContext",
    "PriceEvidence",
    "PriceVolumeAssessment",
    "PriceVolumeSignalEngine",
    "RecommendationAction",
    "RecommendationCandidate",
    "RecommendationDecision",
    "RecommendationEngine",
    "RecommendationEvidence",
    "RecommendationReport",
    "RecommendationRisk",
    "RecommendationScore",
    "RecommendationScoreBreakdown",
    "RecommendationScoringEngine",
    "RecommendationTradePlan",
    "SetupQualityAssessment",
    "VolumeEvidence",
]
