"""Deterministic recommendation intelligence primitives.

M14 converts market intelligence, strategy evidence, empirical probability,
and portfolio context into explainable, auditable recommendation reports.
"""

from __future__ import annotations

from alpha.recommendation_intelligence.engines import (
    CandlePatternEngine,
    EvidenceScoringEngine,
    ExpectedValueEngine,
    OpportunityCostEngine,
    PortfolioAwarenessEngine,
    PriceVolumeSignalEngine,
    RecommendationEngine,
    RecommendationScoringEngine,
    StatisticalEdgeEngine,
    TradePlanIntelligenceEngine,
    TradeSetupEngine,
)
from alpha.recommendation_intelligence.models import (
    AllocationAdjustment,
    CandidateComparison,
    CandlePatternAssessment,
    EdgeConfidence,
    EntryTriggerStyle,
    EntryZoneBasis,
    EntryZoneBasisType,
    EvidenceAssessment,
    EvidenceDirection,
    EvidenceSignal,
    ExpectedValueAssessment,
    HistoricalExpectancy,
    OHLCVBar,
    OpportunityCostAssessment,
    PortfolioContext,
    PriceEvidence,
    PriceVolumeAssessment,
    RecommendationAction,
    RecommendationCandidate,
    RecommendationDecision,
    RecommendationEvidence,
    RecommendationReport,
    RecommendationRisk,
    RecommendationScore,
    RecommendationScoreBreakdown,
    RecommendationTradePlan,
    SetupQualityAssessment,
    StrategyEdgeStats,
    StrategyQuality,
    StrategyRank,
    StrategySuitability,
    TradeSetupAssessment,
    TradeStrategyAction,
    TradeStrategyPlaybook,
    TradeStrategyType,
    TriggerStatus,
    VolumeEvidence,
)

__all__ = [
    "AllocationAdjustment",
    "CandlePatternAssessment",
    "CandlePatternEngine",
    "CandidateComparison",
    "EdgeConfidence",
    "EvidenceAssessment",
    "EvidenceDirection",
    "EvidenceScoringEngine",
    "EvidenceSignal",
    "EntryZoneBasis",
    "EntryZoneBasisType",
    "EntryTriggerStyle",
    "ExpectedValueAssessment",
    "ExpectedValueEngine",
    "HistoricalExpectancy",
    "OpportunityCostAssessment",
    "OpportunityCostEngine",
    "OHLCVBar",
    "PortfolioAwarenessEngine",
    "PortfolioContext",
    "PriceEvidence",
    "PriceVolumeAssessment",
    "PriceVolumeSignalEngine",
    "RecommendationAction",
    "RecommendationCandidate",
    "RecommendationDecision",
    "RecommendationEngine",
    "RecommendationEvidence",
    "RecommendationReport",
    "RecommendationRisk",
    "RecommendationScore",
    "RecommendationScoreBreakdown",
    "RecommendationScoringEngine",
    "RecommendationTradePlan",
    "SetupQualityAssessment",
    "StatisticalEdgeEngine",
    "StrategyEdgeStats",
    "StrategyQuality",
    "StrategyRank",
    "StrategySuitability",
    "TradePlanIntelligenceEngine",
    "TradeStrategyAction",
    "TradeStrategyPlaybook",
    "TradeStrategyType",
    "TradeSetupAssessment",
    "TradeSetupEngine",
    "TriggerStatus",
    "VolumeEvidence",
]
