"""Typed contracts for the governed DSI-002E-J research package."""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class OverrideEligibility(StrEnum):
    OVERRIDE_ELIGIBLE = "OVERRIDE_ELIGIBLE"
    NOT_OVERRIDEABLE_CATEGORICAL = "NOT_OVERRIDEABLE_CATEGORICAL"
    NOT_SEMANTICALLY_VALID = "NOT_SEMANTICALLY_VALID"
    UPSTREAM_INPUT_CHANGE_REQUIRED = "UPSTREAM_INPUT_CHANGE_REQUIRED"
    DOWNSTREAM_STATE_UNDEFINED = "DOWNSTREAM_STATE_UNDEFINED"
    MULTI_CONDITION_EVALUATOR_NOT_ISOLATABLE = (
        "MULTI_CONDITION_EVALUATOR_NOT_ISOLATABLE"
    )
    EVALUATOR_SEAM_UNAVAILABLE = "EVALUATOR_SEAM_UNAVAILABLE"
    PASS_STATE_UNDEFINED = "PASS_STATE_UNDEFINED"
    UNKNOWN_OVERRIDE_ELIGIBILITY = "UNKNOWN_OVERRIDE_ELIGIBILITY"


class DSI002EReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_SINGLE_GATE_SHADOW_RESEARCH"
    PARTIAL = "READY_WITH_PARTIAL_OVERRIDE_ELIGIBILITY"
    D2 = "BLOCKED_BY_DSI002D2_NOT_READY"
    EMPTY = "BLOCKED_BY_NO_OVERRIDE_ELIGIBLE_GATES"
    INVALID = "BLOCKED_BY_INVALID_GATE_OVERRIDE"
    MULTI = "BLOCKED_BY_MULTI_GATE_MUTATION"
    DRIFT = "BLOCKED_BY_PRE_INTERVENTION_DRIFT"
    SEMANTIC = "BLOCKED_BY_DOWNSTREAM_SEMANTIC_INVALIDITY"
    NONDETERMINISTIC = "BLOCKED_BY_SINGLE_GATE_ARM_NONDETERMINISM"
    DIVERGENCE = "BLOCKED_BY_UNEXPLAINED_SINGLE_GATE_DIVERGENCE"
    IMPLEMENTATION = "BLOCKED_BY_GATE_OVERRIDE_IMPLEMENTATION_DEFECT"
    ARTIFACT = "BLOCKED_BY_ARTIFACT_INTEGRITY_DEFECT"


class DSI002FReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_MINIMAL_REMEDIATION_RESEARCH"
    PARTIAL = "READY_WITH_PARTIAL_REMEDIATION_POPULATION"
    E = "BLOCKED_BY_DSI002E_NOT_READY"
    EMPTY = "BLOCKED_BY_NO_VALID_REMEDIATION_SEARCH_POPULATION"
    INCOMPLETE = "BLOCKED_BY_INCOMPLETE_REMEDIATION_SEARCH"
    EXHAUSTED = "BLOCKED_BY_SEARCH_SPACE_EXHAUSTION"
    INVALID = "BLOCKED_BY_INVALID_REMEDIATION_COMBINATION"
    PROOF = "BLOCKED_BY_MINIMALITY_PROOF_DEFECT"
    NONDETERMINISTIC = "BLOCKED_BY_NONDETERMINISTIC_REMEDIATION_RESULT"
    DIVERGENCE = "BLOCKED_BY_UNEXPLAINED_REMEDIATION_DIVERGENCE"
    IMPLEMENTATION = "BLOCKED_BY_REMEDIATION_ENGINE_IMPLEMENTATION_DEFECT"


class DSI002GReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_DOWNSTREAM_SHADOW_RESEARCH"
    ZERO_APPROVAL = "READY_WITH_ZERO_APPROVAL_POPULATION"
    ZERO_TRADE = "READY_WITH_ZERO_TRADE_POPULATION"
    F = "BLOCKED_BY_DSI002F_NOT_READY"
    EMPTY = "BLOCKED_BY_EMPTY_VALID_REMEDIATION_POPULATION"
    APPROVAL = "BLOCKED_BY_APPROVAL_REPLAY_DEFECT"
    ALLOCATION = "BLOCKED_BY_ALLOCATION_REPLAY_DEFECT"
    PORTFOLIO = "BLOCKED_BY_PORTFOLIO_REPLAY_DEFECT"
    ENTRY = "BLOCKED_BY_ENTRY_REPLAY_DEFECT"
    TRADE = "BLOCKED_BY_TRADE_FORMATION_REPLAY_DEFECT"
    PLAN_DRIFT = "BLOCKED_BY_TRADE_PLAN_DRIFT"
    TRANSITION = "BLOCKED_BY_UNEXPLAINED_DOWNSTREAM_TRANSITION"
    ARM = "BLOCKED_BY_UNEXPLAINED_RAW_ADJUSTED_DOWNSTREAM_DIVERGENCE"
    IMPLEMENTATION = "BLOCKED_BY_DOWNSTREAM_REPLAY_IMPLEMENTATION_DEFECT"


class DSI002HReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_GATE_VALUE_RESEARCH"
    DESCRIPTIVE = "READY_WITH_DESCRIPTIVE_OUTCOMES_ONLY"
    NO_OUTCOMES = "READY_WITH_NO_COMPARABLE_COMPLETED_OUTCOMES"
    G = "BLOCKED_BY_DSI002G_NOT_READY"
    LINEAGE = "BLOCKED_BY_OUTCOME_LINEAGE_DEFECT"
    PLAN = "BLOCKED_BY_COUNTERFACTUAL_PLAN_NONCOMPARABILITY"
    POINT_IN_TIME = "BLOCKED_BY_POINT_IN_TIME_LEAKAGE"
    ATTRIBUTION = "BLOCKED_BY_ECONOMIC_ATTRIBUTION_DEFECT"
    ARM = "BLOCKED_BY_UNEXPLAINED_RAW_ADJUSTED_OUTCOME_DIVERGENCE"
    IMPLEMENTATION = "BLOCKED_BY_GATE_VALUE_IMPLEMENTATION_DEFECT"


class DSI002IReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_DSI002_INTERPRETATION"
    DESCRIPTIVE = "READY_WITH_DESCRIPTIVE_INTERPRETATION_ONLY"
    H = "BLOCKED_BY_DSI002H_NOT_READY"
    EMPTY = "BLOCKED_BY_INSUFFICIENT_VALID_ANALYTIC_POPULATION"
    DEPENDENCE = "BLOCKED_BY_UNRESOLVED_DEPENDENCE"
    UNCERTAINTY = "BLOCKED_BY_INVALID_UNCERTAINTY_ESTIMATION"
    MULTIPLE = "BLOCKED_BY_MULTIPLE_TESTING_CONTROL_DEFECT"
    ROBUSTNESS = "BLOCKED_BY_ROBUSTNESS_RECONCILIATION_DEFECT"
    CLAIM = "BLOCKED_BY_UNSUPPORTED_INFERENTIAL_CLAIM"
    IMPLEMENTATION = "BLOCKED_BY_STATISTICAL_IMPLEMENTATION_DEFECT"


class DSI002JReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_DSI002_GATE_ISOLATION_RESEARCH"
    PARTIAL = "READY_WITH_PARTIAL_GATE_ISOLATION_COVERAGE"
    DESCRIPTIVE = "READY_WITH_DESCRIPTIVE_GATE_VALUE_ONLY"
    NO_OUTCOMES = "READY_WITH_VALID_MECHANICS_AND_NO_COMPARABLE_OUTCOMES"
    SOURCE = "BLOCKED_BY_INVALID_DSI002_SOURCE_CHAIN"
    SLICE = "BLOCKED_BY_INTERNAL_SLICE_NOT_READY"
    POPULATION = "BLOCKED_BY_PACKAGE_POPULATION_RECONCILIATION_DEFECT"
    SEMANTIC = "BLOCKED_BY_COUNTERFACTUAL_SEMANTIC_DEFECT"
    OUTCOME = "BLOCKED_BY_OUTCOME_COMPARABILITY_DEFECT"
    DEPENDENCE = "BLOCKED_BY_UNRESOLVED_DEPENDENCE"
    CLAIM = "BLOCKED_BY_UNSUPPORTED_CAUSAL_OR_POLICY_CLAIM"
    ARTIFACT = "BLOCKED_BY_ARTIFACT_INTEGRITY_DEFECT"
    IMPLEMENTATION = "BLOCKED_BY_DSI002_IMPLEMENTATION_DEFECT"


class DownstreamTransition(StrEnum):
    STILL_REJECTED = "STILL_REJECTED"
    INSTITUTIONALLY_APPROVED = "INSTITUTIONALLY_APPROVED"
    APPROVED_BUT_ALLOCATION_SKIPPED = "APPROVED_BUT_ALLOCATION_SKIPPED"
    APPROVED_BUT_PORTFOLIO_INELIGIBLE = "APPROVED_BUT_PORTFOLIO_INELIGIBLE"
    PORTFOLIO_ELIGIBLE_NO_ENTRY = "PORTFOLIO_ELIGIBLE_NO_ENTRY"
    ENTRY_TRIGGER_NOT_REACHED = "ENTRY_TRIGGER_NOT_REACHED"
    ENTRY_FORMED_NO_TRADE = "ENTRY_FORMED_NO_TRADE"
    TRADE_FORMED = "TRADE_FORMED"
    TRADE_FORMED_OUTCOME_PENDING = "TRADE_FORMED_OUTCOME_PENDING"
    SEMANTICALLY_INVALID = "SEMANTICALLY_INVALID"
    UNEXPLAINED_DOWNSTREAM_TRANSITION = "UNEXPLAINED_DOWNSTREAM_TRANSITION"


class OutcomeComparability(StrEnum):
    COMPARABLE_COMPLETED_OUTCOME = "COMPARABLE_COMPLETED_OUTCOME"
    COMPARABLE_NOT_ENTERED = "COMPARABLE_NOT_ENTERED"
    COMPARABLE_PENDING_END_OF_DATA = "COMPARABLE_PENDING_END_OF_DATA"
    MISSING_OUTCOME = "MISSING_OUTCOME"
    PLAN_NOT_COMPARABLE = "PLAN_NOT_COMPARABLE"
    ENTRY_NOT_COMPARABLE = "ENTRY_NOT_COMPARABLE"
    EXECUTION_NOT_COMPARABLE = "EXECUTION_NOT_COMPARABLE"
    COUNTERFACTUAL_PATH_UNOBSERVABLE = "COUNTERFACTUAL_PATH_UNOBSERVABLE"
    ARM_IDENTITY_MISMATCH = "ARM_IDENTITY_MISMATCH"
    OUTCOME_LINEAGE_INVALID = "OUTCOME_LINEAGE_INVALID"
    POINT_IN_TIME_INVALID = "POINT_IN_TIME_INVALID"


class InterpretationGrade(StrEnum):
    DESCRIPTIVE_ONLY = "DESCRIPTIVE_ONLY"
    INSUFFICIENT_SAMPLE = "INSUFFICIENT_SAMPLE"
    HIGH_CONFOUNDING = "HIGH_CONFOUNDING"
    DEPENDENT_OBSERVATIONS = "DEPENDENT_OBSERVATIONS"
    DIRECTIONALLY_STABLE = "DIRECTIONALLY_STABLE_DESCRIPTIVE_RESULT"
    ROBUST = "ROBUST_EXPLORATORY_EVIDENCE"
    SUPPORTED = "STATISTICALLY_SUPPORTED_EXPLORATORY_RESULT"
    NO_CONCLUSION = "NO_RELIABLE_GATE_VALUE_CONCLUSION"


@dataclass(frozen=True, slots=True)
class RenewedSourceBoundary:
    boundary: str
    contract_version: str
    certificate_sha256: str
    report_sha256: str
    readiness: str
    candidate_identity: str
    snapshot_sha256: str
    source_commit: str


@dataclass(frozen=True, slots=True)
class GateIsolationShadowResult:
    source_commit: str
    candidate_identity: str
    snapshot_sha256: str
    sources: tuple[RenewedSourceBoundary, ...]
    rows: dict[str, tuple[dict[str, object], ...]]
    e_readiness: DSI002EReadiness
    f_readiness: DSI002FReadiness
    g_readiness: DSI002GReadiness
    h_readiness: DSI002HReadiness
    i_readiness: DSI002IReadiness
    j_readiness: DSI002JReadiness
    blockers: tuple[str, ...]

    def __post_init__(self) -> None:
        if not self.candidate_identity or not self.snapshot_sha256:
            raise ValueError("DSI-002 E-J requires a non-empty signed population")
        if not self.sources:
            raise ValueError("DSI-002 E-J requires signed source boundaries")
