"""Typed research-only models for DSI-003 population certification."""

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path
from types import MappingProxyType

DSI003_CONTRACT_VERSION = "DSI-003-v1.0.0"
DSI003_RESEARCH_SCOPE = "GOVERNED_INDEPENDENT_POPULATION_EXPANSION_DIAGNOSTIC_ONLY"


class PopulationExpansionError(ValueError):
    """Raised when DSI-003 cannot preserve its governed evidence boundary."""


class PopulationSourceReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_POPULATION_ASSEMBLY"
    INVALID_CHAIN = "BLOCKED_BY_INVALID_SOURCE_CHAIN"
    NO_SOURCE = "BLOCKED_BY_NO_ADMISSIBLE_CANDIDATE_SOURCE"
    INCOMPATIBLE_IDENTITIES = "BLOCKED_BY_INCOMPATIBLE_CANDIDATE_IDENTITIES"
    INCOMPLETE_INVENTORY = "BLOCKED_BY_INCOMPLETE_SOURCE_INVENTORY"
    IMPLEMENTATION = "BLOCKED_BY_POPULATION_SOURCE_IMPLEMENTATION_DEFECT"


class CompleteStackReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_COMPLETE_STACK_POPULATION"
    PARTIAL = "READY_WITH_PARTIAL_COMPLETE_STACK_COVERAGE"
    SOURCE = "BLOCKED_BY_DSI003A_NOT_READY"
    EMPTY = "BLOCKED_BY_EMPTY_COMPLETE_STACK_POPULATION"
    RECONSTRUCTION = "BLOCKED_BY_CANDIDATE_RECONSTRUCTION_DEFECT"
    TERMINAL = "BLOCKED_BY_INCOMPLETE_TERMINAL_RECONCILIATION"
    DUPLICATE = "BLOCKED_BY_DUPLICATE_ECONOMIC_CANDIDATES"
    LEAKAGE = "BLOCKED_BY_POINT_IN_TIME_LEAKAGE"
    ARM_IDENTITY = "BLOCKED_BY_RAW_ADJUSTED_IDENTITY_DEFECT"
    DIVERGENCE = "BLOCKED_BY_UNEXPLAINED_COMPLETE_STACK_DIVERGENCE"


class PopulationBottleneckReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_POPULATION_BOTTLENECK_RESEARCH"
    STACK = "BLOCKED_BY_DSI003B_NOT_READY"
    FUNNEL = "BLOCKED_BY_INCOMPLETE_POPULATION_FUNNEL"
    UNATTRIBUTED = "BLOCKED_BY_UNATTRIBUTED_POPULATION_LOSS"
    SILENT_DROP = "BLOCKED_BY_SILENT_CANDIDATE_DROP"
    RECONCILIATION = "BLOCKED_BY_POPULATION_COUNT_RECONCILIATION_DEFECT"
    IMPLEMENTATION = "BLOCKED_BY_BOTTLENECK_ATTRIBUTION_IMPLEMENTATION_DEFECT"


class IndependenceReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_INDEPENDENT_POPULATION"
    WARNINGS = "READY_WITH_DEPENDENCE_WARNINGS"
    FUNNEL = "BLOCKED_BY_DSI003C_NOT_READY"
    DUPLICATES = "BLOCKED_BY_UNRESOLVED_DUPLICATE_IDENTITIES"
    CANDIDATES = "BLOCKED_BY_CONFLICTING_CANDIDATE_RECORDS"
    DECISIONS = "BLOCKED_BY_CONFLICTING_DECISION_RECORDS"
    OUTCOMES = "BLOCKED_BY_CONFLICTING_OUTCOME_RECORDS"
    IMPLEMENTATION = "BLOCKED_BY_INDEPENDENCE_CERTIFICATION_DEFECT"


class ExternalValidityReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_EXTERNAL_VALIDITY_ASSESSMENT"
    LIMITED = "READY_WITH_LIMITED_EXTERNAL_VALIDITY"
    INDEPENDENCE = "BLOCKED_BY_DSI003D_NOT_READY"
    METADATA = "BLOCKED_BY_INSUFFICIENT_COVERAGE_METADATA"
    CONCENTRATION = "BLOCKED_BY_UNRESOLVED_POPULATION_CONCENTRATION"
    IMPLEMENTATION = "BLOCKED_BY_EXTERNAL_VALIDITY_IMPLEMENTATION_DEFECT"


class OutcomeReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_OUTCOME_POPULATION_RESEARCH"
    LIMITED = "READY_WITH_LIMITED_OUTCOME_COVERAGE"
    NONE = "READY_WITH_NO_COMPLETED_OUTCOMES"
    COVERAGE = "BLOCKED_BY_DSI003E_NOT_READY"
    LINEAGE = "BLOCKED_BY_OUTCOME_LINEAGE_DEFECT"
    LEAKAGE = "BLOCKED_BY_POINT_IN_TIME_OUTCOME_LEAKAGE"
    RECONCILIATION = "BLOCKED_BY_OUTCOME_POPULATION_RECONCILIATION_DEFECT"
    IMPLEMENTATION = "BLOCKED_BY_OUTCOME_READINESS_IMPLEMENTATION_DEFECT"


class TransferabilityReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_DSI002_POPULATION_REPLAY"
    PARTIAL = "READY_WITH_PARTIAL_DSI002_TRANSFERABILITY"
    ZERO_APPROVALS = "READY_WITH_ZERO_SHADOW_APPROVALS"
    OUTCOME = "BLOCKED_BY_DSI003F_NOT_READY"
    ENGINE = "BLOCKED_BY_DSI002_ENGINE_INCOMPATIBILITY"
    SEMANTICS = "BLOCKED_BY_UNSUPPORTED_STAGE_SEMANTICS"
    RECONCILIATION = "BLOCKED_BY_BATCH_REPLAY_RECONCILIATION_DEFECT"
    IMPLEMENTATION = "BLOCKED_BY_DSI002_TRANSFERABILITY_IMPLEMENTATION_DEFECT"
    DIVERGENCE = "BLOCKED_BY_UNEXPLAINED_TRANSFER_DIVERGENCE"


class SufficiencyReadiness(StrEnum):
    READY = "READY_FOR_GOVERNED_POPULATION_SUFFICIENCY_CONCLUSION"
    TRANSFER = "BLOCKED_BY_DSI003G_NOT_READY"
    EFFECTIVE_SAMPLE = "BLOCKED_BY_INVALID_EFFECTIVE_SAMPLE_ESTIMATION"
    DEPENDENCE = "BLOCKED_BY_UNRESOLVED_CLUSTER_DEPENDENCE"
    CLAIM = "BLOCKED_BY_UNSUPPORTED_SAMPLE_SUFFICIENCY_CLAIM"
    IMPLEMENTATION = "BLOCKED_BY_POPULATION_STATISTICS_IMPLEMENTATION_DEFECT"


class FinalPopulationReadiness(StrEnum):
    EXPANDED = "READY_FOR_EXPANDED_GOVERNED_DSI_RESEARCH"
    DESCRIPTIVE = "READY_FOR_DESCRIPTIVE_DSI_RESEARCH_ONLY"
    MECHANICAL = "READY_FOR_MECHANICAL_TRANSFERABILITY_RESEARCH_ONLY"
    NO_EXPANSION = "BLOCKED_BY_NO_INDEPENDENT_POPULATION_EXPANSION"
    EXTERNAL_VALIDITY = "BLOCKED_BY_INSUFFICIENT_EXTERNAL_VALIDITY"
    OUTCOMES = "BLOCKED_BY_INSUFFICIENT_OUTCOME_COVERAGE"
    TRANSFER = "BLOCKED_BY_DSI002_TRANSFERABILITY_DEFECT"
    RECONCILIATION = "BLOCKED_BY_POPULATION_RECONCILIATION_DEFECT"
    SOURCE = "BLOCKED_BY_SOURCE_INTEGRITY_DEFECT"
    LEAKAGE = "BLOCKED_BY_POINT_IN_TIME_LEAKAGE"
    IMPLEMENTATION = "BLOCKED_BY_DSI003_IMPLEMENTATION_DEFECT"


class ExternalValidityGrade(StrEnum):
    SINGLE = "SINGLE_CANDIDATE_ONLY"
    CONCENTRATED = "HIGHLY_CONCENTRATED"
    CROSS_SECTION = "LIMITED_CROSS_SECTION"
    TIME = "LIMITED_TIME_COVERAGE"
    SETUP = "LIMITED_SETUP_COVERAGE"
    REGIME = "LIMITED_REGIME_COVERAGE"
    MODERATE = "MODERATE_RESEARCH_COVERAGE"
    BROAD = "BROAD_RESEARCH_COVERAGE"
    UNKNOWN = "EXTERNAL_VALIDITY_NOT_ESTABLISHED"


class ResearchSufficiencyTier(StrEnum):
    NONE = "INSUFFICIENT_FOR_ANY_GATE_VALUE_RESEARCH"
    MECHANICAL = "SUFFICIENT_FOR_MECHANICAL_TRANSFERABILITY_ONLY"
    DESCRIPTIVE = "SUFFICIENT_FOR_DESCRIPTIVE_GATE_VALUE"
    LIMITED = "SUFFICIENT_FOR_LIMITED_EXPLORATORY_COMPARISON"
    BROAD = "SUFFICIENT_FOR_BROADER_EXPLORATORY_RESEARCH"


@dataclass(frozen=True, slots=True)
class PopulationExpansionSourcePaths:
    """Caller-selected certificates for the complete signed source chain."""

    b5_certificate: Path
    b7_certificate: Path
    b10_certificate: Path
    dsi001_certificate: Path
    dsi002a_certificate: Path
    dsi002d1_certificate: Path
    dsi002b2_certificate: Path
    dsi002c2_certificate: Path
    dsi002d2_certificate: Path
    dsi002_certificate: Path


@dataclass(frozen=True, slots=True)
class PopulationExpansionResult:
    """All deterministic empirical rows and governed DSI-003 conclusions."""

    source_commit: str
    readiness: MappingProxyType[str, str]
    summaries: MappingProxyType[str, object]
    rows: MappingProxyType[str, tuple[Mapping[str, object], ...]]
    blockers: tuple[str, ...]

    def __post_init__(self) -> None:
        if not self.source_commit.strip():
            raise ValueError("source commit cannot be empty")
        if tuple(sorted(self.readiness)) != tuple(self.readiness):
            raise ValueError("slice readiness must be sorted")
        if tuple(sorted(self.rows)) != tuple(self.rows):
            raise ValueError("row collections must be sorted")
        if tuple(sorted(set(self.blockers))) != self.blockers:
            raise ValueError("blockers must be unique and sorted")


__all__ = [
    "CompleteStackReadiness",
    "DSI003_CONTRACT_VERSION",
    "DSI003_RESEARCH_SCOPE",
    "ExternalValidityGrade",
    "ExternalValidityReadiness",
    "FinalPopulationReadiness",
    "IndependenceReadiness",
    "OutcomeReadiness",
    "PopulationBottleneckReadiness",
    "PopulationExpansionError",
    "PopulationExpansionResult",
    "PopulationExpansionSourcePaths",
    "PopulationSourceReadiness",
    "ResearchSufficiencyTier",
    "SufficiencyReadiness",
    "TransferabilityReadiness",
]
